version: "3.9"
services:
  db:
    image: "mysql:8"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - "./database/storage:/var/lib/mysql"
      - "./database/init.sql:/docker-entrypoint-initdb.d/1.sql"
    environment:
      MYSQL_ROOT_PASSWORD: root
    container_name: "db"
    ports:
      - "3306:3306"
    expose:
      - 3306

  backend:
    build: ./backend
    ports:
      # Namapuje <host port>:<internal port>
      - "3030:3030"
    depends_on:
      - db
    links:
      # backend a db na jednu "siet", takze backend bude moct komunikovat s db bez toho aby cela db bola expostnuta
      - db
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "80:8080"

  adminer:
    image: "adminer:latest"
    ports:
      - "8080:8080"
    links:
      - db
